<?php

namespace Repository;

/**
 * Comment
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Comment extends \Doctrine\ORM\EntityRepository
{
}
