<?php

namespace Repository;

/**
 * Post
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Post extends \Doctrine\ORM\EntityRepository
{
}
